import Head from 'next/head';

export interface NextHeadProps {
  title?: string;
}

const NextHead = (props: NextHeadProps) => {
  const { title = 'BLOG' } = props;
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default NextHead;
